server:
  port: 2020
  #servlet:
   # context-path: /v10

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
spring:
  main:    allow-bean-definition-overriding: true
  application:
    name: sso-service
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/estore?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 980305
    
  
#mybatis-plush配置
mybatis-plus:
  #别名包  简化类型转化的写法
  type-aliases-package: top.ericson.pojo
  #加载mybatis的映射文件
  mapper-locations: classpath:/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#引入日志
logging:
  pattern:    console: "%d - %msg%n"
  level:
    top.ericson: debug
    top.ericson.mapper: debug
